name: inter_local
channels:
  - defaults
dependencies:
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cycler=0.11.0
  - decorator=5.1.1
  - executing=0.8.3
  - fftw=3.3.9
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - future=0.18.2
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.42.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipython=8.7.0
  - jedi=0.18.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libtiff=4.5.0
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - oauthlib=3.2.1
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - ply=3.11
  - prompt-toolkit=3.0.36
  - protobuf=3.20.1
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - pytorch=1.12.1
  - pytz=2022.7
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.9.3
  - seaborn=0.12.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - toml=0.10.2
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.13
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - werkzeug=2.2.2
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.8
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - filterpy==1.4.5
    - imageio==2.24.0
    - networkx==3.0
    - numpy==1.24.1
    - opencv-python==4.7.0.68
    - pywavelets==1.4.1
    - scikit-image==0.19.3
    - thop==0.1.1-2209072238
    - tifffile==2022.10.10
#prefix: C:\Users\avish\anaconda3\envs\int_loc
